-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 04:03:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema doomtienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `doomtienda` ;

-- -----------------------------------------------------
-- Schema doomtienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doomtienda` DEFAULT CHARACTER SET utf8 ;
USE `doomtienda` ;

-- -----------------------------------------------------
-- Table `doomtienda`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipoPer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doomtienda`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  `idTipo` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idTipo`
    FOREIGN KEY (`idTipo`)
    REFERENCES `doomtienda`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `doomtienda`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`pago` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `Monto` DOUBLE NOT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doomtienda`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre_cli` VARCHAR(45) NOT NULL,
  `Appat_cli` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `correo_cli` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `codigo_targeta` VARCHAR(5) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doomtienda`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`compras` (
  `idCompras` INT(11) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(11) NOT NULL,
  `idPago` INT(11) NOT NULL,
  `FechaCompras` DATE NOT NULL,
  `Monto` DOUBLE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompras`),
  CONSTRAINT `idPago`
    FOREIGN KEY (`idPago`)
    REFERENCES `doomtienda`.`pago` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `doomtienda`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doomtienda`.`detalle_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doomtienda`.`detalle_compras` (
  `idDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NOT NULL,
  `idCompras` INT(11) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `PrecioCompra` DOUBLE NOT NULL,
  PRIMARY KEY (`idDetalle`),
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `doomtienda`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompras`
    FOREIGN KEY (`idCompras`)
    REFERENCES `doomtienda`.`compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `doomtienda`.`table5`
-- -----------------------------------------------------



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
